
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service

mix:
  stage: test
  image: elixir:latest
  before_script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
  script:
    - mix test


build:
  stage: test
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
  - docker:dind
  before_script:
  - docker info
  script:
  - echo "logging in"
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - echo "building the image"
  - echo "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
  - docker build -t registry.gitlab.com/dewetblomerus/quickaverage:$CI_COMMIT_BRANCH --cache-from registry.gitlab.com/dewetblomerus/quickaverage .
  - echo "pushing the image"
  - docker push registry.gitlab.com/dewetblomerus/quickaverage:$CI_COMMIT_BRANCH
