image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
  - echo "logging in"
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - echo "building the image"
  - docker build -t registry.gitlab.com/dewetblomerus/quickaverage:latest --cache-from registry.gitlab.com/dewetblomerus/quickaverage .
  - echo "pushing the image"
  - docker push registry.gitlab.com/dewetblomerus/quickaverage:latest
