
# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

mix:
  stage: test
  image: elixir:latest
  script:
    - mix test


variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  image: docker:latest
  script:
  - echo "logging in"
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - echo "building the image"
  - docker build -t registry.gitlab.com/dewetblomerus/quickaverage:latest --cache-from registry.gitlab.com/dewetblomerus/quickaverage .
  - echo "pushing the image"
  - docker push registry.gitlab.com/dewetblomerus/quickaverage:latest
