version: '3.3'
services:
  quickaverage:
    image: registry.gitlab.com/dewetblomerus/quickaverage:main
    container_name: quickaverage
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    environment:
      - CERT_MODE=${CERT_MODE}
      - HOST=${HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - SITE_ENCRYPT_DB=${SITE_ENCRYPT_DB:-/tmp/site_encrypt_db}
    volumes:
      - ./site_encrypt_db:${SITE_ENCRYPT_DB:-/tmp/site_encrypt_db}
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
