version: "3.3"
services:
  quickaverage:
    image: registry.gitlab.com/dewetblomerus/quickaverage
    container_name: quickaverage
    ports:
      - ${HTTP_PORT:-80}:4000
      - ${HTTPS_PORT:-443}:4001
    environment:
      - HOST=${HOST}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    restart: unless-stopped
