use Mix.Config

use_https = true

config :quick_average,
  username: "asdf",
  password: "asdf",
  use_https: use_https

host =
  if use_https do
    "av.dev"
  else
    "localhost"
  end

config :quick_average, QuickAverageWeb.Endpoint,
  url: [host: host],
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    esbuild:
      {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    npx: [
      "tailwindcss",
      "--input=css/app.css",
      "--output=../priv/static/assets/app.css",
      "--postcss",
      "--watch",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

if use_https do
  config :quick_average, QuickAverageWeb.Endpoint,
    https: [
      port: 4001,
      cipher_suite: :strong
    ]
end

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :quick_average, QuickAverageWeb.Endpoint,
  esbuild:
    {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/quick_average_web/(live|views)/.*(ex)$",
      ~r"lib/quick_average_web/templates/.*(eex)$"
    ]
  ]

config :logger, :console, format: "[$level] $message\n"

config :phoenix, :plug_init_mode, :runtime
